apiVersion: v1
kind: Service
metadata:
  name: {{ include "infinispan-helm-charts.name" . }}
  annotations:
  {{- include "infinispan-helm-charts.annotations" . | nindent 4 }}
  labels:
    app: infinispan-service
    clusterName: {{ include "infinispan-helm-charts.name" . }}
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  {{- include "infinispan-helm-charts.svcLabels" . | nindent 4 }}
spec:
  {{- if or (eq (.Values.deploy.expose.type) "LoadBalancer") (eq (.Values.deploy.expose.type) "NodePort") }}
  type: {{ .Values.deploy.expose.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 11222
      protocol: TCP
      name: infinispan
      {{- if and (eq (.Values.deploy.expose.type) "NodePort") (.Values.deploy.expose.nodePort) }}
      nodePort: {{ .Values.deploy.expose.nodePort }}
      {{- end}}
  selector:
  {{- include "infinispan-helm-charts.selectorLabels" . | nindent 4 }}
